# Generated by Django 5.2.4 on 2025-07-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineApp', '0004_remove_data_prediction_remove_data_text_data_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Text',
            field=models.TextField(default=''),
        ),
    ]
